#!/usr/bin/env python3
"""Patch WebsiteController.php - update index(), create(), edit() methods"""
import sys

with open('controllers/WebsiteController.php', 'r') as f:
    content = f.read()

changes = 0

# ── index() ──────────────────────────────────────────────────────────────────
OLD = (
    "        // Get and sanitize input parameters with proper null checks\n"
    "        $search = trim($_GET['search'] ?? '');\n"
    "        $sort = $_GET['sort'] ?? 'domain';\n"
    "        $order = isset($_GET['order']) && strtoupper($_GET['order']) === 'DESC' ? 'DESC' : 'ASC';\n"
    "        $page = isset($_GET['page']) ? max(1, (int)$_GET['page']) : 1;\n"
    "        $perPage = isset($_GET['per_page']) ? (int)$_GET['per_page'] : 10;\n"
    "\n"
    "        // Validate per_page options\n"
    "        $allowedPerPage = [10, 30, 50];\n"
    "        if (!in_array($perPage, $allowedPerPage)) {\n"
    "            $perPage = 10;\n"
    "        }\n"
    "\n"
    "        // Validate sort column to prevent SQL injection\n"
    "        $allowedSorts = ['hosting_server', 'domain', 'service_type', 'status', 'expiry_date', 'created_at'];\n"
    "        if (!in_array($sort, $allowedSorts)) {\n"
    "            $sort = 'domain';\n"
    "        }\n"
    "\n"
    "        // Get websites with automatic secondary sorting by domain\n"
    "        $websites = $this->websiteModel->getWebsites($search, $sort, $order, $page, $perPage);\n"
    "\n"
    "        // Calculate dynamic status for each website\n"
    "        foreach ($websites as &$website) {\n"
    "            $website['dynamic_status'] = $this->websiteModel->calculateDynamicStatus($website['expiry_date']);\n"
    "        }\n"
    "        unset($website); // Break the reference\n"
    "\n"
    "        // Pagination calculations with zero-division protection\n"
    "        $totalWebsites = (int)$this->websiteModel->getWebsiteCount($search);\n"
    "        $totalPages = $perPage > 0 ? max(1, ceil($totalWebsites / $perPage)) : 1;\n"
    "\n"
    "        // Get hosting plans for dropdowns (if needed)\n"
    "        $hostingPlans = $this->hostingModel->getAllHostingPlans();\n"
    "\n"
    "        // Pass data to view\n"
    "        require APP_PATH . '/views/websites/index.php';"
)
NEW = (
    "        // Input parameters\n"
    "        $search  = trim($_GET['search'] ?? '');\n"
    "        $page    = isset($_GET['page'])     ? max(1, (int)$_GET['page'])     : 1;\n"
    "        $perPage = isset($_GET['per_page']) ? (int)$_GET['per_page']         : 10;\n"
    "        if (!in_array($perPage, [10, 30, 50])) { $perPage = 10; }\n"
    "\n"
    "        // Domain-centric grouped summaries\n"
    "        $domainSummaries = $this->websiteModel->getDomainSummaries($search, $page, $perPage);\n"
    "\n"
    "        // Annotate days_left and computed status for each service column\n"
    "        $today = new DateTimeImmutable('today');\n"
    "        foreach ($domainSummaries as &$row) {\n"
    "            foreach (['dom', 'web', 'mail'] as $prefix) {\n"
    "                $expiry = $row[\"{$prefix}_expiry\"] ?? null;\n"
    "                if ($expiry) {\n"
    "                    $diff = $today->diff(new DateTimeImmutable($expiry));\n"
    "                    $days = $diff->invert ? -$diff->days : $diff->days;\n"
    "                    $row[\"{$prefix}_days_left\"]       = $days;\n"
    "                    $row[\"{$prefix}_computed_status\"] = $days < 0 ? 'expired' : ($days <= 30 ? 'expiring_soon' : 'active');\n"
    "                } else {\n"
    "                    $row[\"{$prefix}_days_left\"]       = null;\n"
    "                    $row[\"{$prefix}_computed_status\"] = null;\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        unset($row);\n"
    "\n"
    "        $totalDomains = $this->websiteModel->getDomainCount($search);\n"
    "        $totalPages   = $perPage > 0 ? max(1, ceil($totalDomains / $perPage)) : 1;\n"
    "        $userRole     = $_SESSION['role'] ?? $_SESSION['user_role'] ?? 'viewer';\n"
    "\n"
    "        require APP_PATH . '/views/websites/index.php';"
)
if OLD in content:
    content = content.replace(OLD, NEW, 1)
    changes += 1
    print("index() OK")
else:
    print("WARN: index() pattern not matched")

# ── create() POST block + form load ──────────────────────────────────────────
OLD2 = (
    "        if ($_SERVER['REQUEST_METHOD'] === 'POST') {\n"
    "            $data = [\n"
    "                'name' => $_POST['name'],\n"
    "                'domain' => $_POST['domain'],\n"
    "                'service_type' => $_POST['service_type'] ?? 'hosting_web',\n"
    "                'hosting_id' => $_POST['hosting_id'] ?? null,\n"
    "                'email_server' => $_POST['email_server'],\n"
    "                'expiry_date' => $_POST['expiry_date'],\n"
    "                'status' => $_POST['status'],\n"
    "                'vendita' => $_POST['vendita'],\n"
    "                'proprietario' => $_POST['proprietario'] ?? null,\n"
    "                'dns' => $_POST['dns'] ?? null,\n"
    "                'cpanel' => $_POST['cpanel'] ?? null,\n"
    "                'epanel' => $_POST['epanel'] ?? null,\n"
    "                'notes' => $_POST['notes'] ?? null,\n"
    "                'remark' => $_POST['remark'] ?? null\n"
    "            ];\n"
    "\n"
    "            // Validate selected client when provided.\n"
    "            if (!empty($data['hosting_id'])) {\n"
    "                $hostingPlan = $this->hostingModel->getHostingPlanById($data['hosting_id']);\n"
    "                if ($hostingPlan) {\n"
    "                    $data['assigned_email'] = $hostingPlan['email_address'] ?? '';\n"
    "                } else {\n"
    "                    $error = \"Il client selezionato non \u00e8 stato trovato\";\n"
    "                    $website = array_merge($website, $_POST);\n"
    "                    $hostingPlans = $this->hostingModel->getAllHostingPlans();\n"
    "                    require APP_PATH . '/views/websites/form.php';\n"
    "                    return;\n"
    "                }\n"
    "            } else {\n"
    "                $data['assigned_email'] = ''; // No hosting plan selected\n"
    "            }\n"
    "\n"
    "            try {\n"
    "                $this->websiteModel->createWebsite($data);\n"
    "                $_SESSION['message'] = \"Servizio ('{$data['domain']}') creato con successo\";\n"
    "                header('Location: index.php?action=websites');\n"
    "                exit;\n"
    "            } catch (PDOException $e) {\n"
    "                $error = \"Errore durante la creazione del servizio: \" . $e->getMessage();\n"
    "                $website = array_merge($website, $_POST); // Preserve form input\n"
    "            }\n"
    "        }\n"
    "\n"
    "        $hostingPlans = $this->hostingModel->getAllHostingPlans();\n"
    "        require APP_PATH . '/views/websites/form.php';\n"
    "    }"
)
NEW2 = (
    "        if ($_SERVER['REQUEST_METHOD'] === 'POST') {\n"
    "            $data = [\n"
    "                'domain'             => trim($_POST['domain'] ?? ''),\n"
    "                'service_type'       => $_POST['service_type']       ?? 'hosting_web',\n"
    "                'hosting_id'         => $_POST['hosting_id']         ?? null,\n"
    "                'hosting_account_id' => $_POST['hosting_account_id'] ?? null,\n"
    "                'provider_id'        => $_POST['provider_id']        ?? null,\n"
    "                'expiry_date'        => $_POST['expiry_date']        ?? null,\n"
    "                'status'             => 'active',\n"
    "                'notes'              => $_POST['notes']               ?? '',\n"
    "            ];\n"
    "\n"
    "            if (empty($data['domain'])) {\n"
    "                $error = 'Domain is required.';\n"
    "            } else {\n"
    "                try {\n"
    "                    $this->websiteModel->createWebsite($data);\n"
    "                    $_SESSION['message'] = \"Service '{$data['domain']}' created successfully.\";\n"
    "                    header('Location: index.php?action=websites');\n"
    "                    exit;\n"
    "                } catch (PDOException $e) {\n"
    "                    $error = 'Error creating service: ' . $e->getMessage();\n"
    "                    $website = array_merge($website, $_POST);\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "\n"
    "        $hostingPlans    = $this->hostingModel->getAllHostingPlans();\n"
    "        $hostingAccounts = $this->pdo->query(\"\n"
    "            SELECT ha.id, ha.cpanel_username, ha.package_name, h.name AS client_name, p.name AS provider_name\n"
    "            FROM hosting_accounts ha\n"
    "            LEFT JOIN hosting  h ON h.id  = ha.client_id\n"
    "            LEFT JOIN providers p ON p.id = ha.provider_id\n"
    "            WHERE ha.status = 'active'\n"
    "            ORDER BY h.name, ha.cpanel_username\n"
    "        \")->fetchAll(PDO::FETCH_ASSOC);\n"
    "        $registrars    = $this->pdo->query(\"SELECT id, name FROM providers WHERE type = 'registrar' AND is_active = 1 ORDER BY name\")->fetchAll(PDO::FETCH_ASSOC);\n"
    "        $mailProviders = $this->pdo->query(\"SELECT id, name FROM providers WHERE type = 'email'    AND is_active = 1 ORDER BY name\")->fetchAll(PDO::FETCH_ASSOC);\n"
    "        require APP_PATH . '/views/websites/form.php';\n"
    "    }"
)
if OLD2 in content:
    content = content.replace(OLD2, NEW2, 1)
    changes += 1
    print("create() OK")
else:
    print("WARN: create() pattern not matched")

# ── edit() POST block + form load ─────────────────────────────────────────────
OLD3 = (
    "        if ($_SERVER['REQUEST_METHOD'] === 'POST') {\n"
    "            $data = [\n"
    "                'name' => $_POST['name'],\n"
    "                'domain' => $_POST['domain'],\n"
    "                'service_type' => $_POST['service_type'] ?? 'hosting_web',\n"
    "                'hosting_id' => $_POST['hosting_id'] ?? null,\n"
    "                'email_server' => $_POST['email_server'],\n"
    "                'expiry_date' => $_POST['expiry_date'],\n"
    "                'status' => $_POST['status'],\n"
    "                'vendita' => $_POST['vendita'],\n"
    "                'proprietario' => $_POST['proprietario'] ?? null,\n"
    "                'dns' => $_POST['dns'] ?? null,\n"
    "                'cpanel' => $_POST['cpanel'] ?? null,\n"
    "                'epanel' => $_POST['epanel'] ?? null,\n"
    "                'notes' => $_POST['notes'] ?? null,\n"
    "                'remark' => $_POST['remark'] ?? null\n"
    "            ];\n"
    "\n"
    "            // Validate selected client when provided.\n"
    "            if (!empty($data['hosting_id'])) {\n"
    "                $hostingPlan = $this->hostingModel->getHostingPlanById($data['hosting_id']);\n"
    "                if ($hostingPlan) {\n"
    "                    $data['assigned_email'] = $hostingPlan['email_address'] ?? '';\n"
    "                } else {\n"
    "                    $error = \"Selected hosting plan not found\";\n"
    "                    $hostingPlans = $this->hostingModel->getAllHostingPlans();\n"
    "                    require APP_PATH . '/views/websites/form.php';\n"
    "                    return;\n"
    "                }\n"
    "            } else {\n"
    "                $data['assigned_email'] = ''; // No hosting plan selected\n"
    "            }\n"
    "\n"
    "            try {\n"
    "                $this->websiteModel->updateWebsite($id, $data);\n"
    "                $_SESSION['message'] = \"Il servizio '{$data['domain']}' \u00e8 stato aggiornato con successo\";\n"
    "                header('Location: index.php?action=websites&do=view&id=' . $website['id']);\n"
    "                exit;\n"
    "            } catch (PDOException $e) {\n"
    "                $error = \"Errore durante l'aggiornamento del servizio:  '{$data['domain']}'  \" . $e->getMessage();\n"
    "            }\n"
    "        }\n"
    "\n"
    "        $hostingPlans = $this->hostingModel->getAllHostingPlans();\n"
    "        require APP_PATH . '/views/websites/form.php';"
)
NEW3 = (
    "        if ($_SERVER['REQUEST_METHOD'] === 'POST') {\n"
    "            $data = [\n"
    "                'domain'             => trim($_POST['domain'] ?? ''),\n"
    "                'service_type'       => $_POST['service_type']       ?? 'hosting_web',\n"
    "                'hosting_id'         => $_POST['hosting_id']         ?? null,\n"
    "                'hosting_account_id' => $_POST['hosting_account_id'] ?? null,\n"
    "                'provider_id'        => $_POST['provider_id']        ?? null,\n"
    "                'expiry_date'        => $_POST['expiry_date']        ?? null,\n"
    "                'status'             => 'active',\n"
    "                'notes'              => $_POST['notes']               ?? '',\n"
    "            ];\n"
    "\n"
    "            try {\n"
    "                $this->websiteModel->updateWebsite($id, $data);\n"
    "                $_SESSION['message'] = \"Service '{$data['domain']}' updated successfully.\";\n"
    "                header('Location: index.php?action=websites');\n"
    "                exit;\n"
    "            } catch (PDOException $e) {\n"
    "                $error = 'Error updating service: ' . $e->getMessage();\n"
    "            }\n"
    "        }\n"
    "\n"
    "        $hostingPlans    = $this->hostingModel->getAllHostingPlans();\n"
    "        $hostingAccounts = $this->pdo->query(\"\n"
    "            SELECT ha.id, ha.cpanel_username, ha.package_name, h.name AS client_name, p.name AS provider_name\n"
    "            FROM hosting_accounts ha\n"
    "            LEFT JOIN hosting  h ON h.id  = ha.client_id\n"
    "            LEFT JOIN providers p ON p.id = ha.provider_id\n"
    "            WHERE ha.status = 'active'\n"
    "            ORDER BY h.name, ha.cpanel_username\n"
    "        \")->fetchAll(PDO::FETCH_ASSOC);\n"
    "        $registrars    = $this->pdo->query(\"SELECT id, name FROM providers WHERE type = 'registrar' AND is_active = 1 ORDER BY name\")->fetchAll(PDO::FETCH_ASSOC);\n"
    "        $mailProviders = $this->pdo->query(\"SELECT id, name FROM providers WHERE type = 'email'    AND is_active = 1 ORDER BY name\")->fetchAll(PDO::FETCH_ASSOC);\n"
    "        require APP_PATH . '/views/websites/form.php';"
)
if OLD3 in content:
    content = content.replace(OLD3, NEW3, 1)
    changes += 1
    print("edit() OK")
else:
    print("WARN: edit() pattern not matched")

with open('controllers/WebsiteController.php', 'w') as f:
    f.write(content)

print(f"Done. {changes}/3 changes applied.")
sys.exit(0 if changes == 3 else 1)
