<?php
// Database Configuration - generated by installer
// bootstrap.php uses this $dbConfig array to create the PDO connection.
$dbConfig = [
    'host'     => 'localhost',
    'port'     => 3306,
    'username' => 'root',
    'password' => '',
    'database' => 'website_manager',
    'charset'  => 'utf8mb4'
];

